ALTER TYPE "ActivityType" ADD VALUE 'TASK_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'COLUMN_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'COLUMN_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'COLUMN_REORDERED';
ALTER TYPE "ActivityType" ADD VALUE 'COLUMN_DELETED';